# MongoDB connection URI
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodorder

# Enable schema initialization (applicable to SQL databases, not MongoDB)
spring:
  datasource:
    initialization-mode: always
